### PR TITLE
adds dirty plugins and urls

### PR DESCRIPTION
**Pull request by shadowslasher410**

### CODE REVIEW

**Comment by WrinklyNinja** [comment]
The whitespace you added on lines 16205 and 25155 are breaking the masterlist, please fix them.

**Comment by shadowslasher410** [comment]
D'oh! Sorry about that! I'll make the corrections right now!

**Comment by WrinklyNinja** [comment]
The problem is still present on line 16205.

**Comment by shadowslasher410** [comment]
Yeah, I was gonna push a corrected version up but then my internet went down (i'm in the process of switching routers AND internet providers. Yay...)

**Comment by shadowslasher410** [comment]
AAANND... that's the wrong one... ignore that. Luckily, I finally figured out how to test my changes on my own, so hopefully there'll be no more fails. I'll correct it after I take my dog out :)

**Comment by shadowslasher410** [comment]
I tested it in LOOT and it works! YAY! Besides the white spaces, There was an apostrophe in one of the plugins that kept throwing it off - apparently I had to put the apostrophe twice to get it to register as a literal (just like in regex!). Sorry about all the fails and errors and stuff... I'm new at this (although you probably figured that out already :)

**Comment by WrinklyNinja** [comment]
Travis is still complaining about what looks like two tabs on line 16205, which is otherwise blank.

**Comment by shadowslasher410** [comment]
Okay, it should work now

**Comment by WrinklyNinja** [comment]
OK, I've merged this in manually after squashing your commits into one.

**Pull request closed without merging**
